language:
  - python

python:
  -2.6
  - 2.7

install:
  - if [[ $TRAVIS_PYTHON_VERSION == 2.7 ]];
    then pip install pytest-cov python-coveralls;
    else pip install pytest;
    fi
  - pip install pep8

script:
  - pep8 exerciseTDD
  - if [[ $TRAVIS_PYTHON_VERSION == 2.7 ]];
    then py.test -vv exerciseTDD.py --cov exerciseTDD;
    else py.test -vv exerciseTDD;
    fi

after_success:
  - if [[ $TRAVIS_PYTHON_VERSION == 2.7 ]];
    then coveralls;
    fi

notifications:
  email: false